### ISSUE TITLE
Not showing/select repeated values

### ISSUE THREAD

**Issue by wviana** [selectize/selectize.js#1055] opened 2016-05-02 14:10 UTC
I have a select using selective.js

There is some repeated values that shows as just one value.
This is not really my problem. I don't really matter with each one the user selected.
The only thing that I matter is that when sowing the updated content. It shows as empty if the selected value is on that have more than one entry.

Any tip about how to solve it ?

**Comment by joallard** [comment] 2016-05-10 17:43
I don't really follow your description. Do you have a specific issue with Selectize to report?

**Comment by joallard** [comment] 2016-06-23 18:01
Dupe of #129 maybe?

**Comment by wviana** [comment] 2016-06-24 12:19
That's it.

**Comment by joallard** [comment] 2016-06-24 19:45
Alright thanks! If you haven't done so please go +1-vote the issue, the votes are taken into account for priority of fixing.

**Closed as completed by joallard** 2016-06-24 19:45 UTC
