### ISSUE TITLE
Turkish characters not working(like "İ" or "ı")

### ISSUE THREAD

**Issue by rajaz-tr** [selectize/selectize.js#1057] opened 2016-05-05 08:08 UTC
In Turkish we have "ı" character in additon to "i". And in uppercase "ı" becomes "I" and "i" becomes "İ".

For example if have "İstanbul" in my list and if i type "İ" nothing happens. I guess it happens because this plugin uses Javascript keyCode function to detect what is typed and keyCode does not support non ASCII characters? Is there a way to fix this issue?

**Comment by Ca-aC** [comment] 2016-06-18 13:47
Any update on this? Capital i ("İ") does not register. "Ç" and "Ş" do, though.

**Comment by joallard** [comment] 2016-06-22 20:02
The updates are what we see. The status is currently `cause unknown`, so someone needs to go in debugger and find out the cause.

**Comment by kadir950** [comment] 2016-06-30 22:55
@grinninglich   change 'i': '[iÌÍÎÏìíîïĪī]'  To    'i': '[iÌÍÎÏìíîïĪīİ]'  in selectize.js  (add upper i (İ) in the string). I solved problem with this way.

**Comment by brianreavis** [comment] 2016-07-02 16:17
@grinninglich @Ca-aC @kadir950 This should be fixed by sifter 0.5.1: https://github.com/brianreavis/sifter.js/commit/46a8b557266f20aaab49e601751a85563c845a01

**Closed as completed by brianreavis** 2016-07-02 16:17 UTC
Labels: cause unknown
