### ISSUE TITLE
Typing @ gives jerk in text.

### ISSUE THREAD

**Issue by hrishiv90** [selectize/selectize.js#979] opened 2016-01-07 15:16 UTC
When we press "@" or "?" key in text field for new entry or searching an entry the text typed in input box gives jerk for one time at left side.
The text moves little onto left and comes back to normal position this happens every time when we press "@" or "?" key.

**Comment by joallard** [comment] 2016-01-07 16:25
Duplicate of #809. Thank you

**Closed as completed by joallard** 2016-01-07 16:25 UTC
