### ISSUE TITLE
allowEmptyOption is not working

### ISSUE THREAD

**Issue by rmartev** [selectize/selectize.js#967] opened 2015-12-09 13:58 UTC
Hello, 

I've tried to use the setting "allowEmptyOption" so I could have an empty option in my select, but it is not working. 
I've also tried downloaded the examples and after running examples/basic.htm I cannot see the option "None" in the select. 

Is there a problem with newer versions supporting this setting?

Best Regards

**Comment by joallard** [comment] 2016-01-03 05:24
Are you able to show us an example on Jsfiddle/Codepen?

**Comment by rmartev** [comment] 2016-01-06 15:59
@joallard ,
As I said, the problem is reproducible even in the file from examples. 
Anyway, here you can see it, too: https://jsfiddle.net/rosenmartev/jfbhqtcs/

**Comment by joallard** [comment] 2016-01-06 17:55
Sorry about that, I have a bad attention span. Indeed that's weird.

**Comment by mcavalletto** [comment] 2016-01-26 02:48
There are proposed fixes for this bug attached in #739 and #749.

**Comment by rmartev** [comment] 2016-01-26 14:04
@mcavalletto 
It's a bit off-topic, but could we use the "allowEmptyOption" while we set the options of the select programatically? The placeholder is visible when there is no item is selected, but there is no an "empty option" displayed

**Comment by mcavalletto** [comment] 2016-01-26 17:46
@rmartev: I haven't tested this extensively, but because the problem is in the `registerOption` method, I believe it affects both options loaded from an HTML element and those set via API calls, meaning that one of the fixes from #739 or #749 is required in either case.

**Comment by joallard** [comment] 2016-04-01 19:19
Closing in favor of #739. Thanks @mcavalletto

**Closed as completed by joallard** 2016-04-01 19:19 UTC
Labels: bug

**Comment by mentinghfreightcenter** [comment] 2017-03-31 19:29
I don't know who decided to make allowEmptyOption default to false, but that default behavior goes against how modern select boxes work out-of-the-box. Thus, I am forced to use the option whenever I create a new select box, setting allowEmptyOption to true. I'm pretty sure most other developers are forced to do the same. Also, if I leave allowEmptyOption as false, the select box height shrinks, since there is no item div in the DOM yet.

**Comment by joallard** [comment] 2017-04-03 21:43
@mentinghfreightcenter, sure, file an issue
