### ISSUE TITLE
Allow dropdown to open in the "up" direction (and "auto")

### ISSUE THREAD

**Issue by brianreavis** [selectize/selectize.js#29] opened 2013-06-08 18:49 UTC
``` js
dropdownDirection: "auto" | "up" | "down"
```

(handle within `positionDropdown` method)

**Comment by lancedikson** [comment] 2015-03-31 07:38
+1

**Comment by gwezerek** [comment] 2015-05-03 04:21
Tambien, would be a boon.

**Comment by booleanbetrayal** [comment] 2015-05-19 17:09
+1 ... would be great to have the `auto` feature!

**Comment by mrova** [comment] 2015-06-02 13:25
+1!

**Comment by Jackpohare** [comment] 2015-09-01 10:46
+1

**Comment by impworks** [comment] 2015-10-29 15:06
I have created a pull request implementing this feature. If anyone is still interested, you can give it a try.

**Comment by atoftegaard** [comment] 2015-11-12 12:10
@impworks I see several problems with your pull request.
- `dropdownDirection` takes the default value from settings.mode, which is either `single` or `multi` - never auto. You should use a different property for specifying `auto | up | down`.
- `dropdownHeight` is always 0 because you get the value while the dropdown is still hidden. You can only get element sizes when they are visible.
- You do not maintain the borders around the dropdown. Depending on the direction, either top or bottom border should be visible.

After fixing this, I got the results I was looking for.

**Comment by impworks** [comment] 2015-11-12 12:23
@atoftegaard, thank you for your reply. I am sorry for rushing the pull request without having tested it thoroughly myself. I will try to update it and fix the problems.

**Comment by meggers** [comment] 2015-12-03 18:56
@atoftegaard, can you make a PR with your changes?

**Comment by kikonen** [comment] 2015-12-08 11:57
Chances to get this merged?

**Comment by atoftegaard** [comment] 2015-12-09 15:26
I will see if can get to it friday. I have been very busy since I last looked this.

**Comment by atoftegaard** [comment] 2015-12-11 09:56
Sorry but I cannot set aside the time to figure out how to push these 4 lines of code, as I haven't made a pull request before (or a modification to a pull request). I'm sure someone else can do it from my comment.

**Comment by pederjohnsen** [comment] 2016-02-16 15:29
Any reason why this is not yet implemented (seems like a pretty important feature) and are there any working plugins that does this atm?

**Comment by lmi11** [comment] 2016-02-20 19:17
I really need this feature. How to use it in official version of selectize.js?

**Comment by kylej-89** [comment] 2017-02-22 17:57
I have something working for you all that doesn't require a pull request. Just requires some additional logic when implementing your settings. I wrote this pretty quick, seems to work ok but I am bound to have missed something here.

    var exceededWindowHeight = false;

    settings.onDropdownOpen = function ($dropdown) {
        var $control = this.$control;
        var offset = this.settings.dropdownParent === 'body' ? $control.offset() : $control.position();                    

        var windowInnerHeight = window.innerHeight;
        var dropdownHeight = $dropdown.height();

        exceededWindowHeight = (offset.top + dropdownHeight) >= windowInnerHeight;

        // if the offsettop and the dropdown height will extend past the window innerheight then subtract the dropdown height
        // from the offset top as well as the control height
        // If it will not extend past then we can just use the default offset.top
        $dropdown.css({
            top: exceededWindowHeight ? (offset.top - dropdownHeight) : (offset.top + $control.outerHeight(true)),
            borderTop: exceededWindowHeight ? '1px solid #d0d0d0' : '0 none',
            borderRadius: exceededWindowHeight ? '3px 3px 0 0' : '0 0 3px 3px'
        });

        if (exceededWindowHeight) {
            selectize.positionDropdown = (function () {
                return null;
            });
        }
    }

    settings.onType = function () {
        var $control = this.$control;
        var offset = this.settings.dropdownParent === 'body' ? $control.offset() : $control.position();

        var dropdownHeight = selectize.$dropdown.height();

        // if the offsettop and the dropdown height will extend past the window innerheight then subtract the dropdown height
        // from the offset top as well as the control height
        // If it will not extend past then we can just use the default offset.top
        selectize.$dropdown.css({
            top: exceededWindowHeight ? (offset.top - dropdownHeight) : (offset.top + $control.outerHeight(true)),
            borderTop: exceededWindowHeight ? '1px solid #d0d0d0' : '0 none',
            borderRadius: exceededWindowHeight ? '3px 3px 0 0' : '0 0 3px 3px'
        });
    }

**Comment by GendelfLugansk** [comment] 2017-05-12 23:27
Snippet of code that worked for me:

    if (!window.Selectize.prototype.positionDropdownOriginal) {
        window.Selectize.prototype.positionDropdownOriginal = window.Selectize.prototype.positionDropdown;
        window.Selectize.prototype.positionDropdown = function () {
            if (this.settings.dropdownDirection === 'up') {
                let $control = this.$control;
                let offset = this.settings.dropdownParent === 'body' ? $control.offset() : $control.position();

                this.$dropdown.css({
                    width: $control.outerWidth(),
                    top: offset.top - this.$dropdown.outerHeight(),
                    left: offset.left
                });
                this.$dropdown.addClass('direction-' + this.settings.dropdownDirection);
                this.$control.addClass('direction-' + this.settings.dropdownDirection);
                this.$wrapper.addClass('direction-' + this.settings.dropdownDirection);
            } else {
                window.Selectize.prototype.positionDropdownOriginal.apply(this, arguments);
            }
        };
    }

To change dropdown direction, you need to add ``dropdownDirection: 'up'`` to selectize options. Also this code adds css-class 'direction-up' to input, dropdown and wrapper so you can properly style dropdown and input.

**Comment by Augus** [comment] 2018-06-14 15:47
@GendelfLugansk 's answer is cool, maybe using `bottom: 'calc(100%)';` will be better.

```
this.$dropdown.css({
    width: $control.outerWidth(),
     // top: offset.top - this.$dropdown.outerHeight() - 10,
     left: offset.left,
    bottom: 'calc(100% + 4px)'
 });
```

**Comment by MagedSaeed** [comment] 2019-05-10 12:42
Is this feature implemented? or not yet? How can I use it or find a workaround? 
I badly need this feature as the current drop-down goes outside the BrowserWindow of my Electron app.

**Comment by smartconvos** [comment] 2020-01-08 03:01
> 
> 
> Is this feature implemented? or not yet? How can I use it or find a workaround?
> I badly need this feature as the current drop-down goes outside the BrowserWindow of my Electron app.

The answer by GendelfLugansk seems to work well for me.  Make sure you add the selectize option (dropdownDirection: 'up') once you add his code snippet and you should be good to go.

Agreed this should be implemented in the main project but overriding it with this is fine for me right now.

**Closed as completed** 2021-01-18 02:54 UTC
Labels: enhancement, pull request made, no-issue-activity

**Comment by eduardo-mior** [comment] 2021-04-04 21:31
Any definitive solution for that?

**Comment by JimKnoxx** [comment] 2021-08-11 13:49
It would be really nice to get an official supported solution here. So I would appreciate it if the issue is reopened.

**Comment by yurikuzn** [comment] 2022-12-09 12:47
There's an issue with auto-position that the dropdown that is positioned up can overflow the window. Can happen if window height is small. We need it displayed down in such cases as there will be the window scrollbar allowing to scroll down.

The fix can be applied to [here](https://github.com/selectize/selectize.js/blob/v0.15.2/src/plugins/auto_position/plugin.js#L18):

```js
// added
const controlPosBottom = self.$control.get(0).getBoundingClientRect().bottom

// changed
const position =
    controlPosTop + dropdownHeight + wrapperHeight > window.innerHeight &&
    controlPosBottom - dropdownHeight - wrapperHeight >= 0 ?
        POSITION.top :
        POSITION.bottom;
```
