### ISSUE TITLE
Avoid dropdown opening on deletion

### ISSUE THREAD

**Issue by gwacker** [selectize/selectize.js#356] opened 2014-03-29 07:22 UTC
Is there a simple way to avoid the select drop-down opening immediately after deleting an item?

Specifically when using the "remove_button" plugin (clicking the x), but also when using backspace. It just seems like an odd behavior.

A config option to suppress this behavior would be nice.

**Comment by elikrief** [comment] 2015-07-29 10:52
+1

**Comment by mlensment** [comment] 2015-11-20 10:53
Looks like a duplicate of #249

**Comment by risadams** [comment] 2020-11-11 18:31
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Closed as completed by risadams** 2020-11-11 18:31 UTC
