### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mixin' of undefined in 0.12.0.

### ISSUE THREAD

**Issue by nicholasray** [selectize/selectize.js#701] opened 2015-02-02 17:06 UTC
Using version 0.12.0, I get this message in the both the standalone and regular versions. Is there a fix for this?

**Comment by brianreavis** [comment] 2015-02-02 20:43
Hm, are you using require.js or any sort of bundler? The [demo](http://brianreavis.github.io/selectize.js/) site is  using 0.12.0 w/o this problem

**Comment by jacobmhulse** [comment] 2015-04-23 15:38
I just tried to use the stand alone selectize.js and I got the same error at line 535 from `MicroPlugin.mixin(Selectize)`.  It appears `MicroPlugin` is not defined.

My original includes (brace yourself):

```
<script type="text/javascript" language="javascript" src="/Scripts/jquery-2.1.1.js"></script>
<script type="text/javascript" language="javascript" src="/Scripts/jquery-ui-1.11.4.min.js"></script>
<script type="text/javascript" language="javascript" src="/Scripts/jquery.validate.min.js"></script>

<script type="text/javascript" language="javascript" src="/Scripts/bootstrap.js"></script>
<script type="text/javascript" language="javascript" src="/Scripts/bootstrap-switch.js"></script>

<script type="text/javascript" language="javascript" src="/DataTables-1.10.4/media/js/jquery.dataTables.js"></script>
<script type="text/javascript" language="javascript" src="//cdn.datatables.net/plug-ins/3cfcc339e89/integration/bootstrap/3/dataTables.bootstrap.js"></script>
<script type="text/javascript" language="javascript" src="/DataTables-1.10.4/extensions/RowGrouping/jquery.dataTables.grouping.js"></script>
<script type="text/javascript" language="javascript" src="//cdn.datatables.net/responsive/1.0.3/js/dataTables.responsive.js"></script>
<script type="text/javascript" language="javascript" src="//cdn.datatables.net/plug-ins/3cfcc339e89/sorting/enum.js"></script>

<script type="text/javascript" language="javascript" src="/Scripts/jquery.jstepper.min.js"></script>
<script type="text/javascript" language="javascript" src="/Scripts/bootbox.min.js"></script>
<script type="text/javascript" language="javascript" src="/Scripts/fake-select.js"></script>
<script type="text/javascript" language="javascript" src="/Scripts/selectize/selectize.js"></script>
```

This error went away when I moved the include of this file from the bottom of the list to directly under:

```
<script type="text/javascript" language="javascript" src="/Scripts/jquery-2.1.1.js"></script>
<script type="text/javascript" language="javascript" src="/Scripts/jquery-ui-1.11.4.min.js"></script>
<script type="text/javascript" language="javascript" src="/Scripts/jquery.validate.min.js"></script>
```

Hope this helps debug.  Thanks for the great component!

**Comment by haio** [comment] 2016-03-23 02:49
I'm using 0.12.1, standalone bundle works.

**Comment by florentcm** [comment] 2016-03-23 20:50
SAme issue here with 0.12.1 Uncaught TypeError: Cannot read property 'mixin' of undefined

**Comment by twiho** [comment] 2016-04-21 10:57
I'm getting the very same, we do include jquery in our code, but I've tried both standalone and regular, I've tried moving it all around, below, above jquery but I'm still getting the error.
Is there clash between the standalone and jquery?
Do I need a specific version of jquery?
Does it clash with other jquery plugins like jquery.complexify.js, jquery-ui.min.js, jquery.cookie.js and we have multiple others.
Any help is appreciated.

**Comment by hakimihamdan88** [comment] 2016-05-05 07:00
same here Uncaught TypeError: Cannot read property 'mixin' of undefined, error when using this version https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.1/js/selectize.min.js

but no problem when using this https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.1/js/standalone/selectize.js

**Comment by bradical** [comment] 2016-06-23 18:21
I was using 0.12.1/js/standalone/selectize.min.js with requireJS and ran into this problem. Switching to the non-minified version in the standalone directory fixed this for me though I would be interested to know what's going on here. Anyone have any idea?

**Comment by chaitu87** [comment] 2016-07-15 01:28
Including mircoplugin before including selectize solved this for me.

**Comment by joallard** [comment] 2016-07-15 20:27
Can someone confirm that using `js/standalone/selectize.min.js` at 0.12.2, this is still a problem?

**Comment by bojanv91** [comment] 2016-07-16 22:31
Confirming that there is no problem using `js/standalone/selectize.min.js` at 0.12.2.

**Comment by joallard** [comment] 2016-07-20 17:47
Thank you @bojanv91.

Resolution: Make sure to use **standalone** distribution which comes with Microplugin.

**Closed as completed by joallard** 2016-07-20 17:47 UTC
Labels: bug

**Comment by dwasyl** [comment] 2016-07-29 09:05
@joallard Just fyi I faced the same error with 0.12.2, I switched to using the standalone version which fixed the problem (both were min versions).

**Comment by styxxx** [comment] 2016-08-15 09:04
This should be fixed at least by logging some hint on the console. I almost gave up and used another script.

**Comment by joallard** [comment] 2016-08-15 16:06
@styxxx Good point, as I've been quick to point out on other repos, good errors are clear to the cause of the problem and nudge people in how to fix it, which this is neither. However I'm sure you've found just Googling the message will bring you around here.
