### ISSUE TITLE
"selected" className is added but never removed

### ISSUE THREAD

**Issue by croban** [selectize/selectize.js#1191] opened 2016-10-28 16:55 UTC
After selection of one and then another item "selected" class is not removed.
maybe related to [https://github.com/selectize/selectize.js/issues/1154](url)

**Comment by joallard** [comment] 2016-11-03 16:24
Can you make a reproduction case for it?

**Comment by whelaro** [comment] 2016-11-07 20:25
You know, I'm getting the same behavior, although I don't know where the issues arises (may not be selectize):

http://codepen.io/anon/pen/oYJZqy

I'm not sure if it is due to Material Design for Bootstrap, selectize, or me (probably me), but selected retains for me as well.

[the issue I posted to MDoB's tracker](https://github.com/FezVrasta/bootstrap-material-design/issues/1112)

I essentially just worked around it by not having selected have a color and just doing hover event coloring (wasn't personally worried about "current selection" being a different color)

**Comment by joallard** [comment] 2016-11-07 20:56
Thanks @whelaro. Here's the STR we were looking for:
1. Open Codepen
2. Click on selectized input, select Value1
3. Click again, select Value2
4. => Value1 still has `selected` class

I'll accept a fix for this as soon as the next bugfix

**Comment by emilsgulbis** [comment] 2016-11-30 07:36
There is how I handle this.
Temp. solution 
`onDropdownClose: function($dropdown){
    $($dropdown).find('.selected').not('.active').removeClass('selected');
}`

**Comment by whelaro** [comment] 2016-12-16 16:21
@emilsgulbis's temp solution works for me locally and slots in where the commented bit is. I have only tested on single selected options though.

**Comment by rautenull** [comment] 2017-02-02 16:38
I fixed this by adding the following code line above the addition of the 'selected' class inside the refreshOptions function (line 1618):

```
// clear selection on all previously selected elements first
self.$dropdown.find('.selected').removeClass('selected'); 
```
So the final code looks as follows:
```
// clear selection on all previously selected elements first
self.$dropdown.find('.selected').removeClass('selected');
// add "selected" class to selected options
if (!self.settings.hideSelected) {
	for (i = 0, n = self.items.length; i < n; i++) {
		self.getOption(self.items[i]).addClass('selected');
	}
}
```

**Comment by nithrm** [comment] 2017-04-04 20:19
Is there a fix tor this using a plugin? Could I create a plugin to fix this issue?

**Comment by isochronous** [comment] 2017-11-08 17:21
@nithrm If you're going to do anything, just fork the repo, fix the base problem, and submit a pull request.

**Comment by hawaiikaos** [comment] 2018-08-20 16:38
Has this been fixed? I'm still seeing the issue.

**Comment by scrnjakovic** [comment] 2018-10-01 11:52
@hawaiikaos apply @rautenull's code, it will fix it.
Change
```js
// add "selected" class to selected options
if (!self.settings.hideSelected) {
    for (i = 0, n = self.items.length; i < n; i++) {
        self.getOption(self.items[i]).addClass('selected');
    }
}
```
to
```js
// add "selected" class to selected options
if (!self.settings.hideSelected) {
    // clear selection on all previously selected elements first
    self.$dropdown.find('.selected').removeClass('selected');

    for (i = 0, n = self.items.length; i < n; i++) {
        self.getOption(self.items[i]).addClass('selected');
    }
}
```

**Closed as completed** 2020-11-04 15:23 UTC
Labels: bug, pull request welcome
